version: '3.4'
services:
    # uncomment DB services as needed
    db: # PostgreSQL Database
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: your_database
        volumes:
            - ./data:/docker-entrypoint-initdb.d
            - ./.tmp/db:/var/lib/postgresql/data
    # db: # MySQL Database
    #     image: mysql:5.7
    #     command: mysqld --user=root
    #     restart: always
    #     ports:
    #         - "3306:3306"
    #     environment:
    #         MYSQL_ROOT_PASSWORD: password
    #         MYSQL_DATABASE: your_database
    #     volumes:
    #         - ./data:/docker-entrypoint-initdb.d
    web_base: &web_base
        build:
            context: .
            dockerfile: server/Dockerfile
            target: development
        command: sh -c './wait-for db:5432 -- ./node_modules/.bin/nodemon --watch lib --watch server server/index.js' # update db port as needed
        restart: unless-stopped
        env_file: server/.env-docker
        environment:
            - NODE_ENV=development
        ports:
            - 4000:4000
        depends_on:
            - db
    web:
        # hack for docker-compose v3 dropping `extends` support
        << : *web_base
        # allows for hot-reloading of server
        volumes:
            - ./lib:/app/lib
            - ./server:/app/server
            - ./test:/app/test
            - ./package.json:/app/package.json
    test_base: &test_base
        build:
            context: .
            dockerfile: server/Dockerfile
            target: test
        command: sh -c './wait-for db:5432' # update db port as needed
        env_file: server/.env-test
        depends_on:
            - db
    test:
        # hack for docker-compose v3 dropping `extends` support
        << : *test_base
        # allows for hot-reloading of server
        volumes:
            - ./lib:/app/lib
            - ./server:/app/server
            - ./test:/app/test
            - ./package.json:/app/package.json
